import React, { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Camera, Instagram, Mail, Phone, MapPin, Menu, X, Sun, Moon, ExternalLink } from "lucide-react";

// --- Simple image set (replace src with your photos later) ---
const IMAGES = [
  { id: 1, src: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?q=80&w=1600", title: "Eyes of the Wild", category: "Wildlife", location: "Maasai Mara, Kenya" },
  { id: 2, src: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=1600", title: "Glacier Light", category: "Landscape", location: "Patagonia" },
  { id: 3, src: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=1400", title: "Ridge Walk", category: "Nature", location: "Dolomites, Italy" },
  { id: 4, src: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?q=80&w=1600", title: "Forest Breath", category: "Nature", location: "Olympic NP, USA" },
  { id: 5, src: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1600", title: "Golden Dunes", category: "Landscape", location: "Namib Desert" },
  { id: 6, src: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1600", title: "Quiet Confidence", category: "Portraits", location: "Studio" },
  { id: 7, src: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1600", title: "Morning Mist", category: "Nature", location: "Hoh Rainforest" },
  { id: 8, src: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=1600", title: "Stare Down", category: "Wildlife", location: "Sabi Sands, SA" },
  { id: 9, src: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=1600", title: "Edge of Light", category: "Landscape", location: "Iceland" },
  { id: 10, src: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=1600", title: "Portrait in Blue", category: "Portraits", location: "Outdoor" },
  { id: 11, src: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?q=80&w=1200", title: "Whisker Watch", category: "Wildlife", location: "Serengeti" },
  { id: 12, src: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600", title: "Crimson Peak", category: "Landscape", location: "Alps" },
];

const CATEGORIES = ["All", "Wildlife", "Nature", "Landscape", "Portraits"];

export default function NishadAdnanPhotography() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [theme, setTheme] = useState("dark");
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [lightbox, setLightbox] = useState(null); // {id, index}

  useEffect(() => {
    if (theme === "dark") document.documentElement.classList.add("dark");
    else document.documentElement.classList.remove("dark");
  }, [theme]);

  const filtered = useMemo(() => {
    return IMAGES.filter((img) => {
      const matchesCat = category === "All" || img.category === category;
      const matchesQuery = !query || img.title.toLowerCase().includes(query.toLowerCase()) || (img.location || "").toLowerCase().includes(query.toLowerCase());
      return matchesCat && matchesQuery;
    });
  }, [category, query]);

  const openLightbox = (id) => {
    const index = filtered.findIndex((i) => i.id === id);
    setLightbox({ id, index });
  };

  const navigateLightbox = (dir) => {
    if (!lightbox) return;
    const nextIndex = (lightbox.index + dir + filtered.length) % filtered.length;
    setLightbox({ id: filtered[nextIndex].id, index: nextIndex });
  };

  useEffect(() => {
    const onKey = (e) => {
      if (!lightbox) return;
      if (e.key === "Escape") setLightbox(null);
      if (e.key === "ArrowRight") navigateLightbox(1);
      if (e.key === "ArrowLeft") navigateLightbox(-1);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [lightbox, filtered]);

  return (
    <div className="min-h-screen bg-white text-neutral-900 dark:bg-neutral-950 dark:text-neutral-100">
      {/* Navbar */}
      <header className="sticky top-0 z-40 backdrop-blur supports-[backdrop-filter]:bg-white/60 dark:supports-[backdrop-filter]:bg-neutral-900/60 border-b border-neutral-200 dark:border-neutral-800">
        <div className="mx-auto max-w-7xl px-4 md:px-6">
          <div className="flex items-center justify-between h-16">
            <a href="#home" className="flex items-center gap-2 font-semibold tracking-wide">
              <Camera className="h-5 w-5" />
              <span>Nishad Adnan Photography</span>
            </a>
            <nav className="hidden md:flex items-center gap-6 text-sm">
              <a href="#gallery" className="hover:opacity-80">Gallery</a>
              <a href="#about" className="hover:opacity-80">About</a>
              <a href="#contact" className="hover:opacity-80">Contact</a>
              <button onClick={() => setTheme(t => t === "dark" ? "light" : "dark")} className="rounded-full p-2 hover:bg-neutral-200 dark:hover:bg-neutral-800" aria-label="Toggle theme">
                {theme === "dark" ? <Sun className="h-4 w-4"/> : <Moon className="h-4 w-4"/>}
              </button>
            </nav>
            <button className="md:hidden rounded-full p-2 hover:bg-neutral-200 dark:hover:bg-neutral-800" onClick={() => setMenuOpen(true)} aria-label="Open menu">
              <Menu className="h-5 w-5" />
            </button>
          </div>
        </div>
        <AnimatePresence>
          {menuOpen && (
            <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="md:hidden fixed inset-0 bg-black/40" onClick={() => setMenuOpen(false)} />
          )}
          {menuOpen && (
            <motion.div initial={{x: "100%"}} animate={{x:0}} exit={{x:"100%"}} transition={{type:"spring", stiffness:260, damping:24}} className="fixed right-0 top-0 h-full w-72 bg-white dark:bg-neutral-900 shadow-xl border-l border-neutral-200 dark:border-neutral-800 p-6 z-50">
              <div className="flex justify-between items-center mb-6">
                <span className="font-semibold">Menu</span>
                <button onClick={() => setMenuOpen(false)} className="rounded-full p-2 hover:bg-neutral-200 dark:hover:bg-neutral-800" aria-label="Close menu"><X className="h-5 w-5"/></button>
              </div>
              <div className="flex flex-col gap-4">
                <a href="#gallery" onClick={() => setMenuOpen(false)}>Gallery</a>
                <a href="#about" onClick={() => setMenuOpen(false)}>About</a>
                <a href="#contact" onClick={() => setMenuOpen(false)}>Contact</a>
                <button onClick={() => {setTheme(t => t === "dark" ? "light" : "dark"); setMenuOpen(false);}} className="mt-2 inline-flex items-center gap-2 rounded-full px-3 py-2 bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900">
                  {theme === "dark" ? <Sun className="h-4 w-4"/> : <Moon className="h-4 w-4"/>} Toggle theme
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </header>

      {/* Hero */}
      <section id="home" className="relative overflow-hidden">
        <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(60%_60%_at_20%_20%,rgba(120,119,198,0.15),transparent_60%),radial-gradient(40%_40%_at_80%_0%,rgba(255,180,162,0.18),transparent_60%)]"></div>
        <div className="mx-auto max-w-7xl px-4 md:px-6 py-20 md:py-28">
          <div className="grid md:grid-cols-2 gap-10 items-center">
            <div>
              <motion.h1 initial={{y:20, opacity:0}} whileInView={{y:0, opacity:1}} viewport={{once:true}} className="text-4xl md:text-5xl font-bold tracking-tight">
                Nishad Adnan <span className="text-neutral-500 dark:text-neutral-400">Photography</span>
              </motion.h1>
              <motion.p initial={{y:20, opacity:0}} whileInView={{y:0, opacity:1}} viewport={{once:true}} transition={{delay:0.08}} className="mt-4 text-lg text-neutral-600 dark:text-neutral-300">
                Wildlife • Nature • Landscape • Portraits
              </motion.p>
              <div className="mt-6 flex flex-wrap gap-3">
                {CATEGORIES.filter(c => c !== "All").map((c) => (
                  <a key={c} href="#gallery" onClick={() => setCategory(c)} className="rounded-full border border-neutral-300 dark:border-neutral-700 px-3 py-1 text-sm hover:bg-neutral-100 dark:hover:bg-neutral-800">
                    {c}
                  </a>
                ))}
              </div>
              <div className="mt-8 flex flex-wrap gap-4">
                <a href="#gallery" className="inline-flex items-center justify-center rounded-xl px-4 py-2 bg-neutral-900 text-white dark:bg-white dark:text-neutral-900 shadow-sm">View Gallery</a>
                <a href="#contact" className="inline-flex items-center gap-2 rounded-xl px-4 py-2 border border-neutral-300 dark:border-neutral-700 hover:bg-neutral-100 dark:hover:bg-neutral-800">
                  <Mail className="h-4 w-4"/> Book a Session
                </a>
              </div>
            </div>
            <motion.div initial={{scale:1.02, opacity:0}} whileInView={{scale:1, opacity:1}} viewport={{once:true}} className="relative">
              <img src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600" alt="Mountain landscape at golden hour" className="rounded-3xl shadow-2xl w-full object-cover aspect-[4/3]"/>
              <div className="absolute -bottom-5 -left-5 hidden md:block bg-white/80 dark:bg-neutral-900/80 backdrop-blur rounded-2xl p-4 shadow-lg border border-neutral-200 dark:border-neutral-800">
                <div className="text-sm">Based in Denton, TX • Available worldwide</div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Gallery controls */}
      <section id="gallery" className="mx-auto max-w-7xl px-4 md:px-6 py-10">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-6">
          <div>
            <h2 className="text-2xl md:text-3xl font-semibold tracking-tight">Featured Gallery</h2>
            <p className="mt-1 text-neutral-600 dark:text-neutral-300">Browse by category or search titles/locations.</p>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex gap-2">
              {CATEGORIES.map((c) => (
                <button key={c} onClick={() => setCategory(c)} className={`rounded-full px-3 py-1.5 text-sm border ${category === c ? "bg-neutral-900 text-white dark:bg-white dark:text-neutral-900 border-neutral-900 dark:border-white" : "border-neutral-300 dark:border-neutral-700 hover:bg-neutral-100 dark:hover:bg-neutral-800"}`}>
                  {c}
                </button>
              ))}
            </div>
            <div className="relative">
              <input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search…" className="w-56 rounded-xl border border-neutral-300 dark:border-neutral-700 bg-transparent px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-neutral-400" />
            </div>
          </div>
        </div>

        {/* Gallery grid */}
        <div className="mt-8 columns-1 sm:columns-2 lg:columns-3 gap-5 [column-fill:_balance]">
          <AnimatePresence>
            {filtered.map((img) => (
              <motion.figure key={img.id} layout initial={{opacity:0, y:10}} animate={{opacity:1, y:0}} exit={{opacity:0}} className="group mb-5 break-inside-avoid rounded-2xl overflow-hidden border border-neutral-200 dark:border-neutral-800 bg-neutral-50/40 dark:bg-neutral-900/40">
                <button onClick={() => openLightbox(img.id)} className="relative block w-full focus:outline-none">
                  <img src={img.src} alt={img.title} className="w-full object-cover transition-transform duration-300 group-hover:scale-[1.02]"/>
                  <figcaption className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 to-transparent p-3 text-left">
                    <div className="text-white text-sm font-medium">{img.title}</div>
                    <div className="text-white/80 text-xs">{img.category}{img.location ? ` • ${img.location}` : ""}</div>
                  </figcaption>
                </button>
              </motion.figure>
            ))}
          </AnimatePresence>
        </div>

        {/* Lightbox */}
        <AnimatePresence>
          {lightbox && (
            <motion.div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>
              <div className="absolute top-4 right-4 flex gap-2">
                <button onClick={() => setLightbox(null)} className="rounded-full p-2 bg-white/10 hover:bg-white/20" aria-label="Close"><X className="h-5 w-5 text-white"/></button>
              </div>
              <div className="max-w-6xl w-full">
                <div className="flex items-center justify-between mb-3">
                  <button onClick={() => navigateLightbox(-1)} className="rounded-lg px-3 py-2 bg-white/10 hover:bg-white/20 text-white">Prev</button>
                  <div className="text-white/90 text-sm">Use ← → keys • Esc to close</div>
                  <button onClick={() => navigateLightbox(1)} className="rounded-lg px-3 py-2 bg-white/10 hover:bg-white/20 text-white">Next</button>
                </div>
                <div className="relative aspect-[16/10] w-full overflow-hidden rounded-2xl shadow-2xl border border-white/10">
                  <img src={filtered[lightbox.index].src} alt={filtered[lightbox.index].title} className="h-full w-full object-contain"/>
                </div>
                <div className="mt-3 text-center text-white/90">
                  <div className="font-medium">{filtered[lightbox.index].title}</div>
                  <div className="text-sm text-white/70">{filtered[lightbox.index].category}{filtered[lightbox.index].location ? ` • ${filtered[lightbox.index].location}` : ""}</div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </section>

      {/* About */}
      <section id="about" className="bg-neutral-50 dark:bg-neutral-900/40 border-y border-neutral-200 dark:border-neutral-800">
        <div className="mx-auto max-w-7xl px-4 md:px-6 py-16">
          <div className="grid md:grid-cols-2 gap-10 items-start">
            <img src="https://images.unsplash.com/photo-1542567455-cd733f23fbb1?q=80&w=1400" alt="Photographer holding a camera in nature" className="rounded-3xl shadow-xl w-full object-cover aspect-[4/3]"/>
            <div>
              <h3 className="text-2xl md:text-3xl font-semibold tracking-tight">About Nishad</h3>
              <p className="mt-3 text-neutral-600 dark:text-neutral-300 leading-relaxed">
                I tell stories in light and shadow—from the pause before a predator’s leap to the hush of alpine dawns, and the subtle poise of portrait subjects. My work spans <span className="font-medium">Wildlife</span>, <span className="font-medium">Nature</span>, <span className="font-medium">Landscape</span>, and <span className="font-medium">Portrait</span> photography.
              </p>
              <p className="mt-3 text-neutral-600 dark:text-neutral-300 leading-relaxed">
                I’m based in Denton, Texas and available for local and destination shoots. Prints and licensing available on request.
              </p>
              <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                <div className="flex items-center gap-2"><MapPin className="h-4 w-4"/> Denton, TX • Available worldwide</div>
                <div className="flex items-center gap-2"><ExternalLink className="h-4 w-4"/> Prints • Licensing • Workshops</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Contact */}
      <section id="contact" className="mx-auto max-w-7xl px-4 md:px-6 py-16">
        <div className="grid md:grid-cols-2 gap-10">
          <div>
            <h3 className="text-2xl md:text-3xl font-semibold tracking-tight">Let’s work together</h3>
            <p className="mt-3 text-neutral-600 dark:text-neutral-300">Booking portraits, events, editorial assignments, and guided photo-walks. Share a few details and I’ll get back within 24–48 hours.</p>
            <div className="mt-6 flex flex-col gap-3 text-sm">
              <a href="mailto:hello@nishadadnan.photo" className="flex items-center gap-2 hover:underline"><Mail className="h-4 w-4"/> hello@nishadadnan.photo</a>
              <a href="tel:+19454002599" className="flex items-center gap-2 hover:underline"><Phone className="h-4 w-4"/> +1 (945) 400-2599</a>
              <a href="https://instagram.com" target="_blank" rel="noreferrer" className="flex items-center gap-2 hover:underline"><Instagram className="h-4 w-4"/> @nishad.adnan</a>
            </div>
          </div>

          {/* Simple contact form (static demo) */}
          <form className="rounded-2xl border border-neutral-200 dark:border-neutral-800 p-5 bg-white dark:bg-neutral-950 shadow-sm">
            <div className="grid grid-cols-1 gap-4">
              <div>
                <label className="text-sm">Name</label>
                <input required placeholder="Your name" className="mt-1 w-full rounded-xl border border-neutral-300 dark:border-neutral-700 bg-transparent px-3 py-2 outline-none focus:ring-2 focus:ring-neutral-400"/>
              </div>
              <div>
                <label className="text-sm">Email</label>
                <input type="email" required placeholder="you@example.com" className="mt-1 w-full rounded-xl border border-neutral-300 dark:border-neutral-700 bg-transparent px-3 py-2 outline-none focus:ring-2 focus:ring-neutral-400"/>
              </div>
              <div>
                <label className="text-sm">Project details</label>
                <textarea rows={5} placeholder="Tell me about your shoot…" className="mt-1 w-full rounded-xl border border-neutral-300 dark:border-neutral-700 bg-transparent px-3 py-2 outline-none focus:ring-2 focus:ring-neutral-400"/>
              </div>
              <button type="submit" onClick={(e)=>{e.preventDefault(); alert("Thanks! This demo form is not wired to a backend yet. Replace with your email/Netlify/Formspree.");}} className="rounded-xl px-4 py-2 bg-neutral-900 text-white dark:bg-white dark:text-neutral-900 shadow-sm">Send inquiry</button>
            </div>
          </form>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-neutral-200 dark:border-neutral-800 py-8">
        <div className="mx-auto max-w-7xl px-4 md:px-6 flex flex-col md:flex-row items-center justify-between gap-4 text-sm">
          <div>© {new Date().getFullYear()} Nishad Adnan Photography</div>
          <div className="flex items-center gap-4">
            <a href="#home" className="hover:underline">Home</a>
            <a href="#gallery" className="hover:underline">Gallery</a>
            <a href="#about" className="hover:underline">About</a>
            <a href="#contact" className="hover:underline">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
